version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_WS_URL=ws://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
    networks:
      - dwarka-network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/dwarka_temple
      - ML_SERVICE_URL=http://ml-service:8000
      - PORT=8080
    depends_on:
      - mongo
      - ml-service
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
    networks:
      - dwarka-network

  ml-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.ml
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./ml-service:/app
    networks:
      - dwarka-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dwarka_temple
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - dwarka-network

volumes:
  mongo_data:

networks:
  dwarka-network:
    driver: bridge